### ISSUE TITLE
Spike on websockets / webrtc in ELM

### ISSUE THREAD

**Issue by finnhodgkin** [finnhodgkin/Elm-Online-Offline#1]
We'll need to decide between WebRTC and websockets for our user-connection functionality. 

WebRTC would give more privacy by default (the users are directly and securely connected to one another) but has less browser support and more of a processor hit with lots of connected users.

**Comment by ZooeyMiller** [comment]
We've decided to go for websockets for the initial prototype of the online/offline app as webRTC is surplus to requirements of just seeing if users are online/offline, and for now we want to make this as simple as possible.
Decision was aided by the [elm-lang/websocket](https://github.com/elm-lang/websocket) package as we can do it with no ports/js, whereas with WebRTC we would have to do a lot of the work in JavaScript.
We can definitely implement WebRTC alongside the socket online/offline functionality though.
